### ISSUE TITLE
Craco 7.0.0 without TypeScript

### ISSUE THREAD

**Issue by Nico142** [dilanx/craco#435]
Hello,

I read about the TypeScript rewrite in v7.0.0-alpha.5 and was wondering if Craco dropped the support for projects which are not using TypeScript.
I updated to the latest alpha (alpha.7) and I'm getting this error : `Error: Cannot find module 'typescript'`. Is there a way to get it working again without installing TypeScript?

Thanks and best regards,
Nico

**Comment by dilanx** [comment]
I wonder if the issue is caused by the version bump for `cosmiconfig-typescript-loader`? I bumped the versions of all craco dependencies in the newer alpha versions.

I was able to recreate your issue with yarn, so if anyone does end up figuring out a solution without the need to install ts specifically for craco, feel free to share it here! I'll be able to look into fixing it in a couple of days.

**Comment by Nico142** [comment]
I googled a bit and figured out, that NPM is automatically installing the peerDependencies since version 7.0, which Yarn isn't doing. And typescript is in the peerDependencies list of react-scripts.

@bfaulk96
`npm ls typescript` has an empty response
`npm ls ts-node`: 
```├─┬ @craco/craco@7.0.0-alpha.7
│ └─┬ cosmiconfig-typescript-loader@2.0.2
│   └── ts-node@10.8.2
└─┬ react-scripts@5.0.1
  ├─┬ jest@27.5.1
  │ └─┬ @jest/core@27.5.1
  │   └─┬ jest-config@27.5.1
  │     └── ts-node@10.8.2 deduped
  └─┬ tailwindcss@3.1.4
    └─┬ postcss-load-config@3.1.4
      └── ts-node@10.8.2 deduped
```

@dilanx thanks for the help :)

**Comment by melMass** [comment]
CI's don't actually get peerdeps so this is still an issue for CIs IMO

**Comment by wyh-123** [comment]
you can try **npm install typescript**
